name: Beta Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clean
      run: rm -rf .rust .cargo
    - name: Build
      run: cargo build --verbose --features persistence
    - name: Run tests
      run: cargo test --verbose --features persistence
